// Generated by scripts/generate-api-client.mjs. Do not edit.
// SPDX-License-Identifier: Apache-2.0
export interface ApiInputsV2 {
  readonly runPluginCommand: { readonly path: { readonly pluginId: string; readonly commandId: string; }; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": number; readonly [key: string]: unknown; }; };
  readonly getPluginSurfaces: { readonly path: { readonly workspaceId: string; }; };
  readonly listPluginCatalog: { readonly path?: Record<string, never>; };
  readonly getOpenApi: { readonly path?: Record<string, never>; };
  readonly getHealth: { readonly path?: Record<string, never>; readonly query?: { readonly workspaceId?: string; }; };
  readonly getReadiness: { readonly path?: Record<string, never>; };
  readonly setup: { readonly path?: Record<string, never>; readonly body: {  }; };
  readonly listWorkspaces: { readonly path?: Record<string, never>; };
  readonly createWorkspace: { readonly path?: Record<string, never>; readonly body: { readonly "name": string; readonly "viewMode": "business" | "professional"; readonly "pluginIds": readonly (string)[]; }; };
  readonly getWorkspace: { readonly path: { readonly workspaceId: string; }; };
  readonly updateWorkspace: { readonly path: { readonly workspaceId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "name"?: string; readonly "viewMode"?: "business" | "professional"; }; };
  readonly listWorkspaceMembers: { readonly path: { readonly workspaceId: string; }; };
  readonly setWorkspaceMember: { readonly path: { readonly workspaceId: string; readonly principalId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "workspaceRole": "owner" | "operator" | "reviewer" | "viewer"; }; };
  readonly removeWorkspaceMember: { readonly path: { readonly workspaceId: string; readonly principalId: string; }; readonly body: { readonly "expectedStreamVersion": number; }; };
  readonly getWorkspaceAgentCatalog: { readonly path: { readonly workspaceId: string; }; };
  readonly getWorkspaceHome: { readonly path: { readonly workspaceId: string; }; };
  readonly listThreads: { readonly path: { readonly workspaceId: string; }; };
  readonly createThread: { readonly path: { readonly workspaceId: string; }; readonly body: { readonly "subject": string; readonly "pluginId": string; readonly "resourceRef"?: { readonly "namespace": string; readonly "resourceId": string; }; }; };
  readonly listThreadTurns: { readonly path: { readonly workspaceId: string; readonly threadId: string; }; };
  readonly createTurn: { readonly path: { readonly workspaceId: string; readonly threadId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "message": string; readonly "agentDefinitionId"?: string; readonly "modelBindingId"?: string; readonly "runnerId"?: "builtin" | "claude-cli" | "codex-cli"; }; };
  readonly streamWorkspaceEvents: { readonly path: { readonly workspaceId: string; }; readonly query?: { readonly after?: number; }; };
  readonly commandExecution: { readonly path: { readonly executionId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "command": "follow_up" | "steer" | "cancel" | "resume"; readonly "message"?: string; }; };
  readonly listInbox: { readonly path?: Record<string, never>; readonly query?: { readonly workspaceId?: string; }; };
  readonly retryKeyRevocation: { readonly path: { readonly revocationId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "decision": "retry"; }; };
  readonly listActivity: { readonly path?: Record<string, never>; readonly query: { readonly workspaceId: string; }; };
  readonly decideApproval: { readonly path: { readonly approvalId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "decision": "approve_once" | "deny"; }; };
  readonly listDeliverables: { readonly path?: Record<string, never>; readonly query?: { readonly workspaceId?: string; }; };
  readonly createAssets: { readonly path?: Record<string, never>; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": 0; readonly "attachments": readonly ({ readonly "fileName": string; readonly "mediaType": "text/plain" | "text/markdown" | "application/json" | "text/csv" | "application/pdf" | "image/png" | "image/jpeg" | "image/webp"; readonly "contentBase64": string; readonly "protected"?: boolean; })[]; }; };
  readonly getAsset: { readonly path: { readonly assetId: string; }; };
  readonly deleteAsset: { readonly path: { readonly assetId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "reason": string; }; };
  readonly downloadAsset: { readonly path: { readonly assetId: string; }; };
  readonly listMemories: { readonly path?: Record<string, never>; readonly query?: { readonly workspaceId?: string; readonly namespace?: string; }; };
  readonly proposeMemory: { readonly path?: Record<string, never>; readonly body: { readonly "workspaceId": string; readonly "namespace": string; readonly "resourceId": string; readonly "sourceEventId": string; readonly "scopeType"?: "workspace" | "thread" | "resource" | "principal"; readonly "confidence"?: number; readonly "value": {  readonly [key: string]: unknown; }; readonly "expiresAt"?: string; readonly "derivedFromMemoryId"?: string; readonly "derivedViaShareGrantId"?: string; }; };
  readonly reviseMemoryProposal: { readonly path: { readonly memoryId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "confidence": number; readonly "value": {  readonly [key: string]: unknown; }; }; };
  readonly deleteMemory: { readonly path: { readonly memoryId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "reason": string; }; };
  readonly decideMemory: { readonly path: { readonly memoryId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "decision": "accept" | "reject"; }; };
  readonly listShareGrants: { readonly path?: Record<string, never>; };
  readonly createShareGrant: { readonly path?: Record<string, never>; readonly body: { readonly "memoryId": string; readonly "toNamespace": string; readonly "expectedStreamVersion": number; }; };
  readonly revokeShareGrant: { readonly path: { readonly grantId: string; }; readonly body: { readonly "expectedStreamVersion": number; }; };
  readonly listModelPresets: { readonly path?: Record<string, never>; };
  readonly listModelConnections: { readonly path?: Record<string, never>; };
  readonly createModelConnection: { readonly path?: Record<string, never>; readonly body: { readonly "presetId": "openai" | "deepseek" | "anthropic"; readonly "apiKey": string; readonly "displayName"?: string; }; };
  readonly probeModelConnection: { readonly path: { readonly connectionId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "makeDefault"?: boolean; }; };
  readonly installPlugin: { readonly path?: Record<string, never>; readonly body: { readonly "pluginId": string; readonly "version": string; }; };
  readonly listPluginInstallations: { readonly path?: Record<string, never>; };
  readonly updatePlugin: { readonly path: { readonly pluginId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "version": string; }; };
  readonly purgePlugin: { readonly path: { readonly pluginId: string; }; readonly body: { readonly "expectedStreamVersion": number; }; };
  readonly disablePlugin: { readonly path: { readonly pluginId: string; }; readonly body: { readonly "expectedStreamVersion": number; }; };
  readonly activatePlugin: { readonly path: { readonly workspaceId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "pluginId": string; }; };
  readonly deactivatePlugin: { readonly path: { readonly workspaceId: string; readonly pluginId: string; }; readonly body: { readonly "expectedStreamVersion": number; }; };
  readonly listOpcOpportunities: { readonly path?: Record<string, never>; readonly query: { readonly workspaceId: string; }; };
  readonly createOpcOpportunity: { readonly path?: Record<string, never>; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": 0; readonly "input": string; }; };
  readonly getOpcOpportunity: { readonly path: { readonly opportunityId: string; }; readonly query: { readonly workspaceId: string; }; };
  readonly commandOpcOpportunity: { readonly path: { readonly opportunityId: string; }; readonly body: (unknown) & (unknown); };
  readonly previewOpcDeliverables: { readonly path: { readonly opportunityId: string; }; readonly query: { readonly workspaceId: string; }; };
  readonly exportOpcDeliverables: { readonly path: { readonly opportunityId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly [key: string]: unknown; }; };
  readonly runOpcReadOnlySample: { readonly path?: Record<string, never>; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": 0; }; };
  readonly createCodingRepository: { readonly path?: Record<string, never>; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": 0; readonly "input": string; }; };
  readonly listCodingRepositories: { readonly path?: Record<string, never>; readonly query: { readonly workspaceId: string; }; };
  readonly listCodingTasks: { readonly path?: Record<string, never>; readonly query: { readonly workspaceId: string; }; };
  readonly createCodingTask: { readonly path?: Record<string, never>; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": 0; readonly "input": string; readonly "repositoryId"?: string; }; };
  readonly runCodingReadOnlySample: { readonly path?: Record<string, never>; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": 0; }; };
  readonly listCodingRunners: { readonly path?: Record<string, never>; readonly query: { readonly workspaceId: string; }; };
  readonly inspectCodingRunner: { readonly path: { readonly runnerId: "claude-cli" | "codex-cli"; }; readonly body: { readonly "workspaceId": string; readonly "binaryPath": string; }; };
  readonly confirmCodingRunner: { readonly path: { readonly runnerId: "claude-cli" | "codex-cli"; }; readonly body: { readonly "workspaceId": string; readonly "expectedStreamVersion": number; readonly "binaryPath": string; readonly "version": string; readonly "sha256": string; }; };
  readonly getCodingReconciliation: { readonly path: { readonly executionId: string; }; };
  readonly decideCodingReconciliation: { readonly path: { readonly executionId: string; }; readonly body: { readonly "expectedStreamVersion": number; readonly "expectedCodingStreamVersion": number; readonly "decision": "terminate" | "mark_completed" | "create_new_call"; }; };
}
export const API_INPUT_FIELDS_V2 = {
  "runPluginCommand": [
    {
      "name": "pluginId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "commandId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "getPluginSurfaces": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "listPluginCatalog": [],
  "getOpenApi": [],
  "getHealth": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": false,
      "type": "string"
    }
  ],
  "getReadiness": [],
  "setup": [],
  "listWorkspaces": [],
  "createWorkspace": [
    {
      "type": "string",
      "minLength": 1,
      "name": "name",
      "location": "body",
      "required": true
    },
    {
      "enum": [
        "business",
        "professional"
      ],
      "name": "viewMode",
      "location": "body",
      "required": true
    },
    {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "name": "pluginIds",
      "location": "body",
      "required": true
    }
  ],
  "getWorkspace": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "updateWorkspace": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "name",
      "location": "body",
      "required": false
    },
    {
      "enum": [
        "business",
        "professional"
      ],
      "name": "viewMode",
      "location": "body",
      "required": false
    }
  ],
  "listWorkspaceMembers": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "setWorkspaceMember": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "principalId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "enum": [
        "owner",
        "operator",
        "reviewer",
        "viewer"
      ],
      "name": "workspaceRole",
      "location": "body",
      "required": true
    }
  ],
  "removeWorkspaceMember": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "principalId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "getWorkspaceAgentCatalog": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "getWorkspaceHome": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "listThreads": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "createThread": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "subject",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "pluginId",
      "location": "body",
      "required": true
    },
    {
      "type": "object",
      "required": false,
      "properties": {
        "namespace": {
          "type": "string",
          "minLength": 1
        },
        "resourceId": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false,
      "name": "resourceRef",
      "location": "body"
    }
  ],
  "listThreadTurns": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "threadId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "createTurn": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "threadId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "message",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "agentDefinitionId",
      "location": "body",
      "required": false
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "modelBindingId",
      "location": "body",
      "required": false
    },
    {
      "type": "string",
      "enum": [
        "builtin",
        "claude-cli",
        "codex-cli"
      ],
      "name": "runnerId",
      "location": "body",
      "required": false
    }
  ],
  "streamWorkspaceEvents": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "after",
      "location": "query",
      "required": false,
      "type": "integer",
      "minimum": 0
    }
  ],
  "commandExecution": [
    {
      "name": "executionId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "enum": [
        "follow_up",
        "steer",
        "cancel",
        "resume"
      ],
      "name": "command",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "message",
      "location": "body",
      "required": false
    }
  ],
  "listInbox": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": false,
      "type": "string"
    }
  ],
  "retryKeyRevocation": [
    {
      "name": "revocationId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "const": "retry",
      "name": "decision",
      "location": "body",
      "required": true
    }
  ],
  "listActivity": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": true,
      "type": "string"
    }
  ],
  "decideApproval": [
    {
      "name": "approvalId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "enum": [
        "approve_once",
        "deny"
      ],
      "name": "decision",
      "location": "body",
      "required": true
    }
  ],
  "listDeliverables": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": false,
      "type": "string"
    }
  ],
  "createAssets": [
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "const": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "array",
      "minItems": 1,
      "maxItems": 20,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "fileName",
          "mediaType",
          "contentBase64"
        ],
        "properties": {
          "fileName": {
            "type": "string",
            "minLength": 1
          },
          "mediaType": {
            "type": "string",
            "enum": [
              "text/plain",
              "text/markdown",
              "application/json",
              "text/csv",
              "application/pdf",
              "image/png",
              "image/jpeg",
              "image/webp"
            ]
          },
          "contentBase64": {
            "type": "string",
            "contentEncoding": "base64"
          },
          "protected": {
            "type": "boolean",
            "default": false
          }
        }
      },
      "name": "attachments",
      "location": "body",
      "required": true
    }
  ],
  "getAsset": [
    {
      "name": "assetId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "deleteAsset": [
    {
      "name": "assetId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 1,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "reason",
      "location": "body",
      "required": true
    }
  ],
  "downloadAsset": [
    {
      "name": "assetId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "listMemories": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": false,
      "type": "string"
    },
    {
      "name": "namespace",
      "location": "query",
      "required": false,
      "type": "string"
    }
  ],
  "proposeMemory": [
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "namespace",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "resourceId",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "sourceEventId",
      "location": "body",
      "required": true
    },
    {
      "enum": [
        "workspace",
        "thread",
        "resource",
        "principal"
      ],
      "name": "scopeType",
      "location": "body",
      "required": false
    },
    {
      "type": "number",
      "minimum": 0,
      "maximum": 1,
      "name": "confidence",
      "location": "body",
      "required": false
    },
    {
      "type": "object",
      "additionalProperties": true,
      "name": "value",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "expiresAt",
      "location": "body",
      "required": false
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "derivedFromMemoryId",
      "location": "body",
      "required": false
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "derivedViaShareGrantId",
      "location": "body",
      "required": false
    }
  ],
  "reviseMemoryProposal": [
    {
      "name": "memoryId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "number",
      "minimum": 0,
      "maximum": 1,
      "name": "confidence",
      "location": "body",
      "required": true
    },
    {
      "type": "object",
      "additionalProperties": true,
      "name": "value",
      "location": "body",
      "required": true
    }
  ],
  "deleteMemory": [
    {
      "name": "memoryId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "reason",
      "location": "body",
      "required": true
    }
  ],
  "decideMemory": [
    {
      "name": "memoryId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "enum": [
        "accept",
        "reject"
      ],
      "name": "decision",
      "location": "body",
      "required": true
    }
  ],
  "listShareGrants": [],
  "createShareGrant": [
    {
      "type": "string",
      "minLength": 1,
      "name": "memoryId",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "toNamespace",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "revokeShareGrant": [
    {
      "name": "grantId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "listModelPresets": [],
  "listModelConnections": [],
  "createModelConnection": [
    {
      "enum": [
        "openai",
        "deepseek",
        "anthropic"
      ],
      "name": "presetId",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "apiKey",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "displayName",
      "location": "body",
      "required": false
    }
  ],
  "probeModelConnection": [
    {
      "name": "connectionId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "boolean",
      "name": "makeDefault",
      "location": "body",
      "required": false
    }
  ],
  "installPlugin": [
    {
      "type": "string",
      "minLength": 1,
      "name": "pluginId",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "version",
      "location": "body",
      "required": true
    }
  ],
  "listPluginInstallations": [],
  "updatePlugin": [
    {
      "name": "pluginId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "version",
      "location": "body",
      "required": true
    }
  ],
  "purgePlugin": [
    {
      "name": "pluginId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "disablePlugin": [
    {
      "name": "pluginId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "activatePlugin": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "pluginId",
      "location": "body",
      "required": true
    }
  ],
  "deactivatePlugin": [
    {
      "name": "workspaceId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "pluginId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "listOpcOpportunities": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": true,
      "type": "string"
    }
  ],
  "createOpcOpportunity": [
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "const": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "input",
      "location": "body",
      "required": true
    }
  ],
  "getOpcOpportunity": [
    {
      "name": "opportunityId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "workspaceId",
      "location": "query",
      "required": true,
      "type": "string"
    }
  ],
  "commandOpcOpportunity": [
    {
      "name": "opportunityId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "minimum": 1,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "command",
      "location": "body",
      "required": true
    },
    {
      "type": "object",
      "additionalProperties": true,
      "name": "input",
      "location": "body",
      "required": true
    }
  ],
  "previewOpcDeliverables": [
    {
      "name": "opportunityId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "name": "workspaceId",
      "location": "query",
      "required": true,
      "type": "string"
    }
  ],
  "exportOpcDeliverables": [
    {
      "name": "opportunityId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "runOpcReadOnlySample": [
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "const": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "createCodingRepository": [
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "const": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "input",
      "location": "body",
      "required": true
    }
  ],
  "listCodingRepositories": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": true,
      "type": "string"
    }
  ],
  "listCodingTasks": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": true,
      "type": "string"
    }
  ],
  "createCodingTask": [
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "const": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "input",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "repositoryId",
      "location": "body",
      "required": false
    }
  ],
  "runCodingReadOnlySample": [
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "const": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    }
  ],
  "listCodingRunners": [
    {
      "name": "workspaceId",
      "location": "query",
      "required": true,
      "type": "string"
    }
  ],
  "inspectCodingRunner": [
    {
      "name": "runnerId",
      "location": "path",
      "required": true,
      "type": "string",
      "enum": [
        "claude-cli",
        "codex-cli"
      ]
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "pattern": "^/",
      "name": "binaryPath",
      "location": "body",
      "required": true
    }
  ],
  "confirmCodingRunner": [
    {
      "name": "runnerId",
      "location": "path",
      "required": true,
      "type": "string",
      "enum": [
        "claude-cli",
        "codex-cli"
      ]
    },
    {
      "type": "string",
      "minLength": 1,
      "name": "workspaceId",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "minimum": 0,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "pattern": "^/",
      "name": "binaryPath",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "minLength": 1,
      "maxLength": 256,
      "name": "version",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$",
      "name": "sha256",
      "location": "body",
      "required": true
    }
  ],
  "getCodingReconciliation": [
    {
      "name": "executionId",
      "location": "path",
      "required": true,
      "type": "string"
    }
  ],
  "decideCodingReconciliation": [
    {
      "name": "executionId",
      "location": "path",
      "required": true,
      "type": "string"
    },
    {
      "type": "integer",
      "minimum": 1,
      "name": "expectedStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "integer",
      "minimum": 1,
      "name": "expectedCodingStreamVersion",
      "location": "body",
      "required": true
    },
    {
      "type": "string",
      "enum": [
        "terminate",
        "mark_completed",
        "create_new_call"
      ],
      "name": "decision",
      "location": "body",
      "required": true
    }
  ]
} as const;
