{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "muniu.serviceAccountName" . }}
  labels: {{- include "muniu.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if eq .Values.sandbox.driver "kubernetes" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "muniu.candidateServiceAccountName" . }}
  labels: {{- include "muniu.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "muniu.workerServiceAccountName" . }}
  labels: {{- include "muniu.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "muniu.fullname" . }}-worker-sandbox-controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "muniu.fullname" . }}-worker-sandbox-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "muniu.workerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "muniu.fullname" . }}-worker-sandbox-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "muniu.fullname" . }}-api-sandbox-authority
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "muniu.fullname" . }}-api-sandbox-authority
subjects:
  - kind: ServiceAccount
    name: {{ include "muniu.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "muniu.fullname" . }}-api-sandbox-authority
{{- end }}
