// SPDX-License-Identifier: Apache-2.0

import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import process from "node:process";
import { stringify as stringifyYaml, parse as parseYaml } from "yaml";

const root = process.cwd();
const check = process.argv.includes("--check");
const generated = new Map();
const packageVersion = JSON.parse(await readFile(join(root, "package.json"), "utf8")).version;

function digest(value) {
  return createHash("sha256").update(value).digest("hex");
}

function put(path, content) {
  generated.set(join(root, path), content.endsWith("\n") ? content : `${content}\n`);
}

const cliSource = await readFile(join(root, "apps/cli/src/index.ts"), "utf8");
const help = /function printHelp\(\): void \{\s*console\.log\(`([\s\S]*?)`\);\s*\}/u.exec(cliSource)?.[1];
if (!help) throw new Error("cannot extract CLI help");
put("docs/reference/cli.md", `# CLI reference\n\n<!-- generated by scripts/generate-docs.mjs; do not edit -->\n\n\`\`\`text\n${help}\n\`\`\`\n`);

const routeSources = [
  "apps/api/src/server.ts",
  "apps/api/src/agentSessionRoutes.ts",
  "apps/api/src/enterpriseBuiltinAgentRoutes.ts",
  "apps/api/src/controlPlane.ts",
  "apps/api/src/evidenceRoutes.ts"
];
const routes = [];
for (const path of routeSources) {
  const source = await readFile(join(root, path), "utf8");
  for (const match of source.matchAll(/app\.(get|post|put|patch|delete)\(\s*["'`]([^"'`$]+)["'`]/gu)) {
    routes.push({ method: match[1], path: match[2], source: path });
  }
}
routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
put("docs/reference/api-routes.md", [
  "# API route catalog",
  "",
  "<!-- generated by scripts/generate-docs.mjs; do not edit -->",
  "",
  "| Method | Path | Source |",
  "| --- | --- | --- |",
  ...routes.map((route) => `| ${route.method.toUpperCase()} | \`${route.path}\` | \`${route.source}\` |`)
].join("\n"));

const paths = {};
for (const route of routes) {
  const path = route.path.replace(/:([A-Za-z0-9_]+)/gu, "{$1}");
  paths[path] ??= {};
  paths[path][route.method] = {
    operationId: `${route.method}_${path.replace(/[^A-Za-z0-9]+/gu, "_")}`,
    responses: { "200": { description: "Successful response" } },
    "x-muniu-source": route.source
  };
}
put("docs/reference/openapi.yaml", stringifyYaml({
  openapi: "3.1.0",
  info: { title: "Muniu API", version: packageVersion },
  servers: [{ url: "http://127.0.0.1:7318" }],
  paths
}));

const coreTypes = await readFile(join(root, "packages/core/src/types.ts"), "utf8");
const runtimeTypes = await readFile(join(root, "packages/runtime/src/types.ts"), "utf8");
const eventNames = [...new Set(
  [...coreTypes.matchAll(/type:\s*["']([^"']+)["']/gu), ...runtimeTypes.matchAll(/\|\s*["']([^"']+)["']/gu)]
    .map((match) => match[1])
    .filter((value) => value.includes(".") || value.includes("_") || value.includes("/"))
)].sort();
put("docs/reference/events.md", `# Event catalog\n\n<!-- generated by scripts/generate-docs.mjs; do not edit -->\n\n${eventNames.map((name) => `- \`${name}\``).join("\n")}\n`);

const toolsSource = await readFile(join(root, "packages/agent-tools/src/workspace-tools.ts"), "utf8");
const toolNames = [...toolsSource.matchAll(/name:\s*["']([^"']+)["']/gu)].map((match) => match[1]);
put("docs/reference/tools.md", `# Builtin workspace tools\n\n<!-- generated by scripts/generate-docs.mjs; do not edit -->\n\n${toolNames.map((name) => `- \`${name}\``).join("\n")}\n`);

const profileNames = ["local", "enterprise-api", "enterprise-worker", "desktop"];
const profileRows = [];
for (const name of profileNames) {
  const path = `config/runtime/profiles/${name}.yml`;
  const raw = await readFile(join(root, path), "utf8");
  const entries = parseYaml(raw);
  profileRows.push(`| \`${name}\` | ${entries.map((entry) => `\`${entry.id}\``).join(", ")} | \`${digest(raw)}\` |`);
}
put("docs/reference/plugins.md", [
  "# Builtin profile/plugin catalog",
  "",
  "<!-- generated by scripts/generate-docs.mjs; do not edit -->",
  "",
  "| Profile | Entries | Source digest |",
  "| --- | --- | --- |",
  ...profileRows
].join("\n"));

put("docs/reference/configuration.md", [
  "# Configuration reference",
  "",
  "<!-- generated by scripts/generate-docs.mjs; do not edit -->",
  "",
  "Runtime layer order: `base-bundle → deployment-profile → user-directory-patch → cli-patch`.",
  "",
  "Environment overrides: `MN_RUNTIME_PROFILE_PATH`, `MN_RUNTIME_BASE_PATH`, `MN_RUNTIME_CLI_PATCH`, `MN_RUNTIME_HMR`, `MN_MNIU_ROOT`.",
  "",
  "Plugin state: `~/.muniu/runtime/plugins.json`; executable patch: `~/.muniu/runtime/plugins.yml`; audit: `~/.muniu/runtime/plugin-audit.jsonl`."
].join("\n"));

const descriptions = {
  "api": "Fastify API, enterprise control plane, Agent sessions and evidence routes.",
  "cli": "Machine-readable `mn` CLI and enterprise worker entry point.",
  "worker": "Candidate orchestration, Gates, repair loops and sandbox backends.",
  "agent-protocol": "Versioned Agent messages, bindings, events and transport DTOs.",
  "agent-session": "Durable protected sessions and local/remote persistence stores.",
  "agent-llm": "Model adapter and streaming contracts.",
  "agent-tools": "Policy-aware Agent tool registry and workspace tools.",
  "agent-kernel": "Turn/step execution kernel.",
  "agent-host": "Agent lifecycle host and session runner.",
  "core": "Task, strategy, run and policy domain contracts.",
  "runtime": "Cordis profiles, lifecycle audit and Context isolation.",
  "governance": "Monotonic governance layers, packs, waivers and digests.",
  "harness": "Immutable execution manifests and sandbox evidence contracts.",
  "loop": "Governed repair-loop state machine and budgets.",
  "evidence": "Evidence, trace, learning and maturity models.",
  "executors": "Builtin and compatibility runtime executors.",
  "verifier": "Candidate scoring and verification.",
  "connectors": "Repository indexing and service discovery.",
  "provider-catalog": "Provider/model catalog and application projection.",
  "config-manager": "Managed Claude/Codex configuration projection.",
  "extensions": "Skills, MCP and prompt extension registry.",
  "store": "Local file/SQLite stores and secret vault.",
  "local-proxy": "Provider proxy, usage accounting and receipts.",
  "usage": "Usage aggregation and cost summaries.",
  "specs": "Spec revisions, validation and import.",
  "data-policy": "Credential and business-data protection.",
};
for (const parent of ["apps", "packages"]) {
  const { readdir } = await import("node:fs/promises");
  for (const name of await readdir(join(root, parent))) {
    const packagePath = join(root, parent, name, "package.json");
    let pkg;
    try { pkg = JSON.parse(await readFile(packagePath, "utf8")); } catch { continue; }
    if (name === "desktop-mac" || name === "runtime") continue;
    const content = `# ${pkg.name}\n\n${descriptions[name] ?? "Muniu workspace package."}\n\n## Commands\n\n\`\`\`bash\nnpm run build -w ${pkg.name}\nnpm run typecheck -w ${pkg.name}\nnpm run test -w ${pkg.name}\n\`\`\`\n\nThis package is private and versioned with the Muniu monorepo.\n`;
    put(`${parent}/${name}/README.md`, content);
  }
}

let failed = false;
for (const [path, content] of generated) {
  if (check) {
    let current = "";
    try { current = await readFile(path, "utf8"); } catch {}
    if (current !== content) {
      console.error(`stale generated documentation: ${relative(root, path)}`);
      failed = true;
    }
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, "utf8");
  }
}
if (failed) process.exitCode = 1;
